### ISSUE TITLE
Turn off Signed-off-by

### ISSUE THREAD

**Issue by kensington** [monsieurp/Gentoo-App-Pram#4]
Currently Signed-off-by has no meaning in Gentoo, so please turn it off or make it optional.

**Comment by monsieurp** [comment]
Dealt with. See above reference.

**Comment by kensington** [comment]
Thanks a lot!

**Comment by monsieurp** [comment]
In the Gentoo tree now: https://github.com/gentoo/gentoo/commit/227c1df1b15805935a965bdb763d8117773aabca.
